language: ruby
matrix:
  include:
  # 2019.8.5 (LTS)
  - rvm: 2.5.8
    env: PUPPET_VERSION=6.21.1
  # 2019.1.3
  - rvm: 2.5.7
    env: PUPPET_VERSION=6.12.0
  # 2018.1.18
  - rvm: 2.4.9
    env: PUPPET_VERSION=5.5.17
  # 2017.3.1
  - rvm: 2.4.1
    env: PUPPET_VERSION=5.3.1
script:
  - "bundle exec rake spec"
