AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - 'Rakefile'
    - 'Gemfile'
    - 'vendor/**/*'
    - 'examples/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

